hotel/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path

from .views import *

app_name = 'hotel'

urlpatterns = [
    path('create/',
         create_hotel, name='create-hotel'),

    path('show/',
         show_hotel, name='show-hotel'),

    path('ubah/<str:kode>',
         ubah_hotel, name='ubah-hotel'),

    path('create-makan/',
         create_makan, name='create-makan'),

    path('show-makan/',
         show_makan, name='show-makan'),

    path('ubah-makan/<str:kode_hot>/<str:kode_pak>',
         ubah_makan, name='ubah-makan'),

    path('delete-makan/<str:kode_hot>/<str:kode_pak>',
         delete_makan, name='delete-makan'),

    path('create-trans-makan/',
         create_trans_makan, name='create-trans-makan'),

    path('show-trans-makan/',
         show_trans_makan, name='show-trans-makan'),

    path('ubah-trans-makan/',
         ubah_trans_makan, name='ubah-trans-makan'),

    path('detail-trans-makan/<str:idtr>/<str:idtm>',
         detail_trans_makan, name='detail-trans-makan'),

]

siruco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('trigger3/', include ('trigger3.urls')),
    path("", include('dashboard.urls')),
    path('transaksi/', include('transaksi_hotel.urls')),
    path('transaksi/', include('transaksi_rs.urls')),
    path('pasien/', include('hasiltespasien.urls')),
    path("hotel/", include('ruangan_hotel.urls')),
    path("", include('dashboard.urls')),
    path("hotel/", include('ruangan_hotel.urls')),
    path("pengguna-publik/", include('crudpasienpenggunapublik.urls')),
    path("jadwal-dokter/", include('crjadwaldokter.urls')),
    path("appointment/", include('crudappointmentwithdoctor.urls')),
    path("ruangan-bed/", include('crudruanganbed.urls')),
    path('pasien/', include('hasiltespasien.urls')),
    path('hotel/', include('hotel.urls'))
]

hotel/models.py
from django.db import models

# Create your models here.

hotel/views.py
import django.contrib.auth
from django.contrib import auth, messages

from django.contrib.auth import authenticate
from django.db import connection
from django.db.utils import InternalError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from collections import namedtuple


def create_hotel(request):
    rows_count = count_next_id("hotel", "kode", "hot-")
    next_id = "hot-" + str(rows_count)

    cursor = connection.cursor()
    if request.POST:
        kodehotel = next_id
        namahotel = request.POST.get('namahotel')
        isRujukan = request.POST.get('isRujukan', '0')
        jalan = request.POST.get('jalan')
        kelurahan = request.POST.get('kelurahan')
        kecamatan = request.POST.get('kecamatan')
        kota = request.POST.get('kota')
        provinsi = request.POST.get('provinsi')

        print(isRujukan)
        if '' not in (namahotel, isRujukan, jalan, kelurahan, kecamatan, kota, provinsi):
            query = ("INSERT INTO HOTEL VALUES" "('{}', '{}', '{}', '{}','{}', '{}', '{}', '{}')").format(
                next_id, namahotel, isRujukan, jalan, kelurahan, kecamatan, kota, provinsi)
            cursor.execute(query)
            print("isRujukan : " + isRujukan)
            return redirect('hotel:show-hotel')

        messages.error(
            request, 'Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu')
        return redirect(reverse('hotel:create-hotel'))
    return render(request, 'hotel/create-hotel.html', {'next_id': next_id})


def show_hotel(request):
    cursor = connection.cursor()
    query = (
        'SELECT kode, nama, isrujukan, jalan, kelurahan, kecamatan, kabkot, prov FROM HOTEL')
    cursor.execute(query)
    show_hotel = dictfetchall(cursor)
    context = {'list_hotel': show_hotel}
    print(context)
    return render(request, 'hotel/show-hotel.html', context)


def ubah_hotel(request, kode):
    hotel_kode = str(kode)
    cursor = connection.cursor()
    query = ("SELECT * FROM HOTEL WHERE kode= '"+hotel_kode+"'")
    cursor.execute(query)
    ubah_isi = dictfetchall(cursor)
    print(ubah_isi)
    if request.POST:
        namahotel = request.POST.get('namahotel')
        isRujukan = request.POST.get('isRujukan', '0')
        jalan = request.POST.get('jalan')
        kelurahan = request.POST.get('kelurahan')
        kecamatan = request.POST.get('kecamatan')
        kota = request.POST.get('kota')
        provinsi = request.POST.get('provinsi')
        if '' not in (namahotel, jalan, kelurahan, kecamatan, kota, provinsi):
            cursor = connection.cursor()
            query = ("UPDATE HOTEL SET nama =  '"+namahotel+"', isrujukan =  '"+isRujukan+"', jalan =  '"+jalan+"', kelurahan =  '" +
                     kelurahan+"', kecamatan =  '"+kecamatan+"', kabkot =  '"+kota+"', prov =  '"+provinsi+"' WHERE  kode =  '"+hotel_kode+"'")
            print(query)
            cursor.execute(query)
            return redirect('hotel:show-hotel')
        else:
            messages.error(
                request, 'Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu')
            return redirect(reverse('hotel:ubah-hotel', args=(kode,)))
    return render(request, 'hotel/ubah-hotel.html', {'data': ubah_isi[0]})


def create_makan(request):
    cursor = connection.cursor()
    if request.POST:
        kode_hotel = request.POST.get('kode_hotel')
        kode_paket = request.POST.get('kode_paket')
        nama_paket = request.POST.get('nama_paket')
        harga_paket = request.POST.get('harga_paket')

        if '' not in (kode_hotel, kode_paket, nama_paket, harga_paket):
            query = ("INSERT INTO PAKET_MAKAN VALUES"
                     "('{}', '{}', '{}', '{}')").format(kode_hotel, kode_paket, nama_paket, harga_paket)
            print(query)
            cursor.execute(query)
            return redirect(reverse('hotel:show-makan'))
        else:
            print('Ada kosong')
            messages.error(
                request, 'Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu')
            return redirect(reverse('hotel:create-makan'))

    query = ("SELECT kode FROM HOTEL")
    cursor.execute(query)
    res = cursor.fetchall()
    list_kode_hotel = [i[0] for i in res]
    print(list_kode_hotel)
    return render(request, 'hotel/create-makan.html', {"list_kode_hotel": list_kode_hotel})


def show_makan(request):
    cursor = connection.cursor()
    query = ('SELECT kodehotel, kodepaket, nama, harga FROM PAKET_MAKAN')
    cursor.execute(query)
    show_makanan = dictfetchall(cursor)

    query2 = (
        "SELECT * FROM PAKET_MAKAN WHERE kodepaket NOT IN (SELECT kodepaket FROM DAFTAR_PESAN WHERE DAFTAR_PESAN.kodehotel = PAKET_MAKAN.kodehotel AND DAFTAR_PESAN.kodepaket = PAKET_MAKAN.kodepaket)")
    cursor.execute(query2)
    show_delete = dictfetchall(cursor)

    context = {'list_makan': show_makanan, 'list_delete': show_delete}
    print(context)
    return render(request, 'hotel/show-makan.html', context)


def ubah_makan(request, kode_hot, kode_pak):
    hotel_kode = str(kode_hot)
    paket_kode = str(kode_pak)
    cursor = connection.cursor()
    query = ("SELECT * FROM PAKET_MAKAN WHERE kodepaket= '" +
             paket_kode+"' AND kodehotel= '"+hotel_kode+"'")
    cursor.execute(query)
    ubah_isi = dictfetchall(cursor)
    print(ubah_isi)
    if request.POST:
        kode_hotel = hotel_kode
        kode_paket = paket_kode
        nama_paket = request.POST.get('nama_paket')
        harga_paket = request.POST.get('harga_paket')
        if '' not in (nama_paket, harga_paket):
            cursor = connection.cursor()
            query = ("UPDATE PAKET_MAKAN SET nama =  '"+nama_paket+"', harga =  '" +
                     harga_paket+"' WHERE kodehotel= '"+kode_hotel+"' AND kodepaket= '"+kode_paket+"'")
            cursor.execute(query)
            return redirect('hotel:show-makan')
        else:
            messages.error(
                request, 'Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu')
            return redirect(reverse('hotel:ubah-makan', args=(kode_hot, kode_pak,)))
    return render(request, 'hotel/ubah-makan.html', {'data': ubah_isi[0]})


def delete_makan(request, kode_hot, kode_pak):
    hotel_kode = str(kode_hot)
    paket_kode = str(kode_pak)
    cursor = connection.cursor()
    query = ("SELECT * FROM PAKET_MAKAN WHERE kodepaket= '" +
             paket_kode+"' AND kodehotel= '"+hotel_kode+"' AND kodepaket IN (SELECT kodepaket FROM DAFTAR_PESAN) ")
    # print(query)
    cursor.execute(query)
    ubah_isi = namedtuplefetchall(cursor)
    print(ubah_isi)
    if ubah_isi == []:
        cursor = connection.cursor()
        query = ("DELETE FROM PAKET_MAKAN WHERE kodepaket= '"+paket_kode+"'")
        print("keubah")
        cursor.execute(query)
        messages.success(request, 'Data berhasil dihapus')
        return redirect('hotel:show-makan')
    else:
        print('gak bisa di delete')
        messages.error(
            request, 'Data tidak bisa dihapus')
        return redirect('hotel:show-makan')
    return render(request, 'hotel/show-makan.html')


def create_trans_makan(request):
    rows_count = count_next_id("transaksi_makan", "idtransaksimakan", "idm")
    next_id = "idm0" + str(rows_count)
    if rows_count > 9:
        next_id = "idm" + str(rows_count)

    cursor = connection.cursor()
    query = ("SELECT idtransaksi FROM TRANSAKSI_HOTEL")
    cursor.execute(query)
    res = cursor.fetchall()
    list_idtrans = [i[0] for i in res]
    # print(list_idtrans)

    if request.POST:
        idtrans = request.POST.get('idtransaksi')
        idtransmak = next_id

        query = (
            "SELECT kodehotel from reservasi_hotel natural join transaksi_hotel where idtransaksi='"+idtrans+"' ")
        kodehotel = request.POST.get('kodehotel')

        kode_paket = request.POST.get('kodepaket')

        if '' not in (idtrans, idtransmak, kodehotel, kode_paket):
            query = ("INSERT INTO TRANSAKSI_MAKAN VALUES"
                     "('{}', '{}', '{}', '{}')").format(idtrans, idtransmak, kodehotel, kode_paket)
            print(query)
            cursor.execute(query)
            return redirect(reverse('hotel:show-trans-makan'))
        else:
            print('Ada kosong')
            messages.error(
                request, 'Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu')
            return redirect(reverse('hotel:create-trans-makan'))
    context = {"list_idtrans": list_idtrans,
               "next_id": next_id}
    return render(request, 'hotel/create-trans-makan.html', context)


def show_trans_makan(request):
    cursor = connection.cursor()
    query = (
        'SELECT idtransaksi, idtransaksimakan, totalbayar FROM TRANSAKSI_MAKAN')
    cursor.execute(query)
    show_tmakan = dictfetchall(cursor)
    context = {'list_tmakan': show_tmakan}
    print(context)
    return render(request, 'hotel/show-trans-makan.html', context)


def ubah_trans_makan(request):
    return render(request, 'hotel/ubah-trans-makan.html')


def detail_trans_makan(request, idtr, idtm):
    idtransaksi = str(idtr)
    idtransaksimakan = str(idtm)
    cursor = connection.cursor()
    query = (
        "SELECT * FROM DAFTAR_PESAN NATURAL JOIN TRANSAKSI_MAKAN NATURAL JOIN PAKET_MAKAN WHERE idtransaksi= '"+idtransaksi+"' AND idtransaksimakan = '"+idtransaksimakan+"'  ")
    cursor.execute(query)
    detail_transaksi_makan = dictfetchall(cursor)
    context = {'apt': detail_transaksi_makan}
    print(context)
    return render(request, 'hotel/detail-trans-makan.html', context)


def count_next_id(table_name, col_name, prefix):
    with connection.cursor() as cursor:
        cursor.execute("SELECT {} FROM {}".format(col_name, table_name))
        rows = cursor.fetchall()
        if len(rows) == 0:
            return 1
        prefix_len = len(prefix)

hotel/templates/hotel/create-hotel.html
{% extends "root/base.html" %}
{% block content %}

    <div>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
      </div>
      
    <div class="container">
        <div class="card">
            <h5 class="card-header">FORM BUAT HOTEL</h5>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="kodeHotel">Kode Hotel</label>
                        <input type="text" class="form-control" id="kodeHotel" name="kodehotel" value="{{next_id}}" readonly>
                    </div>
        
                    <div class="form-group">
                        <label for="namaHotel">Nama Hotel</label>
                        <input type="text" class="form-control" id="namaHotel" name="namahotel" placeholder="Masukan Nama Hotel">
                    </div>
                    
                    <div class="container">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="isRujukan" name="isRujukan" value="1">
                            <label class="form-check-label" for="isRujukan">Rujukan</label>
                        </div>
                    </div>
        
                    <label>Alamat:</label>
                    <div class="form-group">
                        <label for="jalan">Jalan:</label>
                        <input type="text" class="form-control" id="jalan" name="jalan" placeholder="Masukan Nama Jalan">
                    </div>
        
                    <div class="form-group">
                        <label for="kelurahan">Kelurahan:</label>
                        <input type="text" class="form-control" id="kelurahan" name="kelurahan" placeholder="Masukan Nama Kelurahan">
                    </div>
        
                    <div class="form-group">
                        <label for="kecamatan">Kecamatan:</label>
                        <input type="text" class="form-control" id="kecamatan" name="kecamatan" placeholder="Masukan Nama Kecamatan">
                    </div>
        
                    <div class="form-group">
                        <label for="kota">Kabupaten/Kota:</label>
                        <input type="text" class="form-control" id="kota" name="kota" placeholder="Masukan Nama Kabupaten/Kota">
                    </div>
        
                    <div class="form-group">
                        <label for="provinsi">Provinsi:</label>
                        <input type="text" class="form-control" id="provinsi" name="provinsi" placeholder="Masukan Nama Provinsi">
                    </div>
        
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
          </div>
    </div>

{% endblock %}

hotel/templates/hotel/create-makan.html
{% extends "root/base.html" %}
{% block content %}

  <div>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
  </div>

  <div class="container">
    <div class="card">
        <h5 class="card-header">FORM BUAT PAKET MAKAN</h5>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="kode_hotel">Kode Hotel:</label>
              <select class="form-control" id="kode_hotel" name="kode_hotel">
                {% for kode_hotel in list_kode_hotel %}
                <option value="{{kode_hotel}}">
                  {{kode_hotel}}
                </option>
                {% endfor %}
              </select>
            </div>

            <div class="form-group">
              <label for="kode_paket">Kode Paket :</label>
              <input type="text" class="form-control" id="kode_paket" name="kode_paket" placeholder="Masukan Kode Paket">
            </div>
            <div class="form-group">
              <label for="nama_paket">Nama Paket :</label>
              <input type="text" class="form-control" id="nama_paket" name="nama_paket" placeholder="Masukan Nama Paket">
            </div>
            <div class="form-group">
              <label for="harga">Harga:</label>
              <input type="text" class="form-control" id="harga" name="harga_paket" placeholder="Masukan Harga">
            </div>
            <button type="submit" class="btn btn-primary">Simpan</button>
          </form>
          </form>
        </div>
      </div>
</div>

{% endblock %}

hotel/templates/hotel/create-trans-makan.html
{% extends "root/base.html" %}
{% block content %}
<div>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
  </div>
  
<div class="container">
    <div class="card">
        <h5 class="card-header">FORM BUAT TRANSAKSI MAKAN</h5>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="idtransaksi">id Transaksi:</label>
                    <select class="form-control" id="idtransaksi" name="idtransaksi">
                      {% for idtrans in list_idtrans %}
                      <option value="{{idtrans}}">
                        {{idtrans}}
                      </option>
                      {% endfor %}
                    </select>
                  </div>
    
                <div class="form-group">
                    <label for="idtransaksimakan">Id Transaksi Makan</label>
                    <input type="text" class="form-control" id="idtransaksimakan" name="idtransaksimakan" value="{{next_id}}" readonly>
                </div>

                <div class="form-group">
                    <label for="kodehotel">Kode Hotel</label>
                    <input type="text" class="form-control" id="kodehotel" name="kodehotel">
                </div>
    
                <label>Pesanan:</label>
                <div class="form-group">
                    <label for="kodepaket">Kode Paket:</label>
                    <select class="form-control" id="kodepaket" name="kodepaket">
                      <!-- {% for kode_hotel in list_kode_hotel %}
                      <option value="{{kode_hotel}}">
                        {{kode_hotel}}
                      </option>
                      {% endfor %} -->
                    </select>
                </div>
                
                <button type="submit" class="btn btn-secondary">Tambah</button>

                <button type="submit" class="btn btn-primary">Simpan</button>
            </form>
        </div>
      </div>
</div>



{% endblock %}

hotel/templates/hotel/detail-trans-makan.html
{% extends "root/base.html" %}
{% block title %}
DETAIL TRANSAKSI RS
{% endblock %}
{% block content %}
  
<div class="card">
    <div class="card-header">
      DATA TRANSAKSI MAKAN
    </div>
    <div class="card-body">
      <p class="card-text">
        {% if apt %}
          Id Transaksi: {{apt.0.idtransaksi}}
          <br>
          Id Transaksi Makan: {{apt.0.idtransaksimakan}}
          <br>
          Kode Hotel: {{apt.0.kodehotel}} 
          <br>
          <label>Daftar Pesanan</label>
          <br>

          <table class="table">
            <thead>
              <tr>
                <th scope="col">Id Pesanan</th>
                <th scope="col">Paket Makan</th>
                <th scope="col">Harga</th>
              </tr>
            </thead>
            {% for item in apt %}
            <tbody>
                <tr>
              <td>{{ item.id_pesanan }}</td>
              <td>{{ item.kodepaket }}</td>
              <td>{{ item.harga }}</td>
              </tr>
            </tbody>
            {% endfor %}
          </table>

          <br>
          Total {{apt.0.totalbayar}}
          <br>
        {% endif %}
        </p>
      <a href="{% url 'hotel:show-trans-makan' %}" class="btn btn-primary">KEMBALI</a>
    </div>
  </div>

  {% endblock %}

hotel/templates/hotel/show-hotel.html
{% extends "root/base.html" %}
{% block content %}

  <table class="table">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Kode</th>
        <th scope="col">Hotel</th>
        <th scope="col">Rujukan</th>
        <th scope="col">Alamat</th>
        {% if request.session.authority == "admin sistem" %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    {% for item in list_hotel %}
    <tbody>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ item.kode }}</td>
      <td>{{ item.nama }}</td>
      <td>
        {% if item.isrujukan == "1" %}
          <div class="form-check">
          <input class="form-check-input" type="checkbox" value="1" id="isRujukan" checked="checked" disabled>
          <label class="form-check-label" for="isRujukan">
          </label>
          </div>
        {% endif %}
        {% if item.isrujukan == "0" %}
          <div class="form-check">
          <input class="form-check-input" type="checkbox" value="0" id="isRujukan" disabled>
          <label class="form-check-label" for="isRujukan">
          </label>
          </div>
        {% endif %}
      </td>
      <td>{{ item.jalan }}, {{ item.kelurahan }}, {{ item.kecamatan }}, {{ item.kabkot }}, {{ item.prov }}</td>
      <td>
        {% if request.session.authority == "admin sistem" %}
        <a href="{% url 'hotel:ubah-hotel' kode=item.kode %}">
          <button class="btn btn-warning">UPDATE</button>
        </a>
        {% endif %}
      </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>


  {% endblock %}

hotel/templates/hotel/show-makan.html
{% extends "root/base.html" %}
{% block content %}

<div>
  {% if messages %}
  {% for message in messages %}
  {% if 'success' in message.tags %}
  <div class="alert alert-success">
    {{ message }}
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}
</div>


  <table class="table">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Hotel</th>
        <th scope="col">Kode Paket</th>
        <th scope="col">Nama Paket</th>
        <th scope="col">Harga</th>
        {% if request.session.authority == "admin sistem" %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    {% for item in list_makan %}
    <tbody>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ item.kodehotel }}</td>
      <td>{{ item.kodepaket }}</td>
      <td>{{ item.nama }}</td>
      <td>{{ item.harga }}</td>
      {% if request.session.authority == "admin sistem" %}
      <td>
        <a href="{% url 'hotel:ubah-makan' item.kodehotel item.kodepaket %}">
          <button class="btn btn-warning">UPDATE</button>
        </a>
       
        {% for i in list_delete %}
        {% if item.kodepaket == i.kodepaket and item.kodehotel == i.kodehotel %}
        <a href="{% url 'hotel:delete-makan' item.kodehotel item.kodepaket %}">
          <button class="btn btn-danger">DELETE</button>
        </a>
        {% endif %}
        {% endfor %}
      </td>
      {% endif %}

      </tr>
    </tbody>
    {% endfor %}
  </table>

  {% endblock %}

hotel/templates/hotel/show-trans-makan.html
{% extends "root/base.html" %}
{% block content %}

<div>
    {% if messages %}
    {% for message in messages %}
    {% if 'success' in message.tags %}
    <div class="alert alert-success">
      {{ message }}
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
  </div>
  
    <table class="table">
      <thead>
        <tr>
          <th scope="col">No.</th>
          <th scope="col">Id Transaksi Hotel</th>
          <th scope="col">Id Transaksi</th>
          <th scope="col">Total Bayar</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      {% for item in list_tmakan %}
      <tbody>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{ item.idtransaksi }}</td>
        <td>{{ item.idtransaksimakan }}</td>
        <td>{{ item.totalbayar }}</td>

        <td>
        {% if request.session.authority != "admin sistem" %}
            <a href="{% url 'hotel:detail-trans-makan' idtr=item.idtransaksi idtm=item.idtransaksimakan %}"> 
                <button type="button" class="btn btn-primary">DETAIL</button>
            </a>
        {% endif %}
        {% if request.session.authority == "admin sistem" %}
          <a href="">
            <button class="btn btn-warning">UPDATE</button>
          </a>
          <a href="">
            <button class="btn btn-danger">DELETE</button>
          </a>
          <a href="{% url 'hotel:detail-trans-makan' idtr=item.idtransaksi idtm=item.idtransaksimakan %}">  
            <button type="button" class="btn btn-primary">DETAIL</button>
        </a>
      
        {% endif %}
        </td>
        </tr>
      </tbody>
      {% endfor %}
    </table>

{% endblock %}

hotel/templates/hotel/ubah-hotel.html
{% extends "root/base.html" %}
{% block content %}

	<div>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
      </div>
      
    <div class="container">
        <div class="card">
            <h5 class="card-header">FORM UBAH HOTEL</h5>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="kodeHotel">Kode Hotel</label>
                        <input type="text" class="form-control" id="kodeHotel" name="kodehotel" value="{{data.kode}}" readonly>
                    </div>
        
                    <div class="form-group">
                        <label for="namaHotel">Nama Hotel</label>
                        <input type="text" class="form-control" id="namaHotel" name="namahotel" value="{{data.nama}}">
                    </div>
                    
                    <div class="container">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="isRujukan" name="isRujukan" value="{{data.isrujukan}}">
                            <label class="form-check-label" for="isRujukan">Rujukan</label>
                        </div>
                    </div>
        
                    <label>Alamat:</label>
                    <div class="form-group">
                        <label for="jalan">Jalan:</label>
                        <input type="text" class="form-control" id="jalan" name="jalan" value="{{data.jalan}}">
                    </div>
        
                    <div class="form-group">
                        <label for="kelurahan">Kelurahan:</label>
                        <input type="text" class="form-control" id="kelurahan" name="kelurahan" value="{{data.kelurahan}}">
                    </div>
        
                    <div class="form-group">
                        <label for="kecamatan">Kecamatan:</label>
                        <input type="text" class="form-control" id="kecamatan" name="kecamatan" value="{{data.kecamatan}}">
                    </div>
        
                    <div class="form-group">
                        <label for="kota">Kabupaten/Kota:</label>
                        <input type="text" class="form-control" id="kota" name="kota" value="{{data.kabkot}}">
                    </div>
        
                    <div class="form-group">
                        <label for="provinsi">Provinsi:</label>
                        <input type="text" class="form-control" id="provinsi" name="provinsi" value="{{data.prov}}">
                    </div>
        
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
          </div>
    </div>
	
{% endblock %}

hotel/templates/hotel/ubah-makan.html
{% extends "root/base.html" %}
{% block content %}

  <div>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
  </div>

  <div class="container">
    <div class="card">
        <h5 class="card-header">FORM UBAH PAKET MAKAN</h5>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="kode_hotel">Kode Hotel:</label>
              <input type="text" class="form-control" id="kode_hotel" name="kode_hotel" value="{{data.kodehotel}}" readonly>
             
            </div>

            <div class="form-group">
              <label for="kode_paket">Kode Paket :</label>
              <input type="text" class="form-control" id="kode_paket" name="kode_paket" value="{{data.kodepaket}}" readonly>
            </div>

            <div class="form-group">
              <label for="nama_paket">Nama Paket :</label>
              <input type="text" class="form-control" id="nama_paket" name="nama_paket" value="{{data.nama}}">
            </div>
            
            <div class="form-group">
              <label for="harga">Harga:</label>
              <input type="text" class="form-control" id="harga" name="harga_paket" value="{{data.harga}}">
            </div>
            <button type="submit" class="btn btn-primary">Simpan</button>
          </form>
          </form>
        </div>
      </div>
</div>

{% endblock %}

hotel/templates/hotel/ubah-trans-makan.html
{% extends "root/base.html" %}
{% block content %}



{% endblock %}