hotel/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path

from .views import *

app_name = 'hotel'

urlpatterns = [
    path('create/',
         create_hotel, name='create-hotel'),

    path('show/',
         show_hotel, name='show-hotel'),

    path('ubah/<str:kode>',
         ubah_hotel, name='ubah-hotel'),

    path('create-makan/',
         create_makan, name='create-makan'),

    path('show-makan/',
         show_makan, name='show-makan'),

    path('ubah-makan/<str:kode_hot>/<str:kode_pak>',
         ubah_makan, name='ubah-makan'),

    path('delete-makan/<str:kode_hot>/<str:kode_pak>',
         delete_makan, name='delete-makan'),

    path('create-trans-makan/',
         create_trans_makan, name='create-trans-makan'),

    path('show-trans-makan/',
         show_trans_makan, name='show-trans-makan'),

    path('ubah-trans-makan/',
         ubah_trans_makan, name='ubah-trans-makan'),

    path('detail-trans-makan/<str:idtr>/<str:idtm>',
         detail_trans_makan, name='detail-trans-makan'),

]

ruangan_hotel/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from . import views
from ruangan_hotel.views import booking_ruangan_hotel

app_name = 'ruangan_hotel'

urlpatterns = [
    path('booking_ruangan_hotel/',views.booking_ruangan_hotel, name='booking_ruangan_hotel'),
    path('list_ruangan_hotel/',views.show_ruangan_hotel, name='show_ruangan_hotel'),
    path('reservasi_hotel/',views.buat_reservasi_hotel, name='buat_reservasi_hotel'),
    path('list_reservasi_hotel/',views.show_reservasi_hotel, name='show_reservasi_hotel'),
    path('list_transaksi_hotel/',views.show_transaksi_hotel,name='show_transaksi_hotel'),
    path('list_transaksi_hotel/<str:id>',views.show_ubah_transaksi_hotel,name='show_ubah_transaksi_hotel'),
    path('list_transaksi_booking/',views.show_transaksi_booking,name='show_transaksi_booking'),
]

siruco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('trigger3/', include ('trigger3.urls')),
    path("", include('dashboard.urls')),
    path('transaksi/', include('transaksi_hotel.urls')),
    path('transaksi/', include('transaksi_rs.urls')),
    path('pasien/', include('hasiltespasien.urls')),
    path("hotel/", include('ruangan_hotel.urls')),
    path("", include('dashboard.urls')),
    path("hotel/", include('ruangan_hotel.urls')),
    path("pengguna-publik/", include('crudpasienpenggunapublik.urls')),
    path("jadwal-dokter/", include('crjadwaldokter.urls')),
    path("appointment/", include('crudappointmentwithdoctor.urls')),
    path("ruangan-bed/", include('crudruanganbed.urls')),
    path('pasien/', include('hasiltespasien.urls')),
    path('hotel/', include('hotel.urls'))
]

ruangan_hotel/models.py
from django.db import models

# Create your models here.

ruangan_hotel/views.py
from django import forms
from django.db import connection
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from collections import namedtuple

# def booking_ruangan_hotel(request):
#     cursor = connection.cursor()
#     cursor.execute("set search_path to siruco;")
#     cursor.execute("select kode from hotel;")
#     kh_response = dictfetch(cursor)
#     context = {'apt' : kh_response}

#     if(request.method == "POST"):
#         kodehotel = request.POST.get('kodehotel')
#         jenis_bed = request.POST.get('jenis_bed')
#         tipe = request.POST.get('tipe')
#         harga = request.POST.get('harga')
#         cursor.execute("INSERT INTO HOTEL_ROOM(kodehotel, , jenisbed, tipe, harga")

#     return render(request, 'form_ruangan.html', context)

# def booking_ruangan_hotel(request):
#     cursor = connection.cursor()
#     cursor.execute("set search_path to siruco;")
#     cursor.execute("select kode from hotel;")
#     kh_response = dictfetch(cursor)
#     context = {'apt' : kh_response}

#     if(request.method == "POST"):
#         kodehotel = request.POST.get('kodehotel')
#         jenis_bed = request.POST.get('jenis_bed')
#         tipe = request.POST.get('tipe')
#         harga = request.POST.get('harga')
#         cursor.execute("INSERT INTO HOTEL_ROOM(kodehotel, , jenisbed, tipe, harga")

#     return render(request, 'form_ruangan.html', context)

def dictfetch(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def count_next_id(table_name, col_name, prefix):
    with connection.cursor() as cursor:
        cursor.execute("SELECT {} FROM {}".format(col_name, table_name))
        rows = cursor.fetchall()
        if len(rows) == 0:
            return 1
        prefix_len = len(prefix)
        return max(int(row[0][prefix_len:]) for row in rows if row[0][:prefix_len] == prefix) + 1
    return None

def booking_ruangan_hotel(request):
    rows_count = count_next_id("hotel_room", "koderoom", "hr-")
    next_id = "hr-" + str(rows_count)
    kh_response = get_kodehotel()
    context = {'apt' : kh_response}
    cursor = connection.cursor()

    if request.POST:
        kodehotel =  request.POST.get('kodehotel') 
        koderoom = next_id
        jenis_bed = request.POST.get('jenisbed')
        tipe = request.POST.get('tipe')
        harga = request.POST.get('harga')
        
        if '' not in (kodehotel, koderoom, jenis_bed, tipe, harga):
            query = ("INSERT INTO HOTEL_ROOM VALUES" "('{}', '{}', '{}', '{}','{}')").format(
                kodehotel, next_id, jenis_bed, tipe, harga)
            cursor.execute(query)
            # return redirect('ruangan_hotel:show_ruangan_hotel')
            return redirect(reverse('ruangan_hotel:show_ruangan_hotel'))

        else:
            messages.error(request, 'Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu')
            return redirect(reverse('ruangan_hotel:booking_ruangan_hotel'))
    return render(request, 'form_ruangan.html', context)

def buat_reservasi_hotel(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco;")
    cursor.execute("select nik from pasien;")
    nik_response = dictfetch(cursor)
    kh_response = get_kodehotel()
    kr_response = get_koderoom()
    context = {'nik' : nik_response, 'kh' : kh_response, 'kr' : kr_response}

    if(request.method == "POST"):
        nik = request.POST.get('nik')
        tanggalmasuk = request.POST.get('tanggalmasuk')
        tanggalkeluar = request.POST.get('tanggalkeluar')
        kodehotel = request.POST.get('kodehotel')
        koderoom = request.POST.get('koderoom')
        if '' not in (nik, tanggalmasuk, tanggalkeluar, kodehotel, koderoom):
            query = ("INSERT INTO RESERVASI_HOTEL VALUES" "('{}', '{}', '{}', '{}','{}')").format(nik, tanggalmasuk, tanggalkeluar, kodehotel, koderoom)
            cursor.execute(query)
            return redirect('ruangan_hotel:show_reservasi_hotel')

        else:
            messages.error(request, 'Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu')
            return redirect(reverse('ruangan_hotel:buat_reservasi_hotel'))

    return render(request, 'reservasi_hotel.html', context)  

def update_transaksi_hotel(request):
    cursor = connection.cursor()
    if(request.method == "POST"):
        statusbayar = request.POST.get('statusbayar')
        if '' not in (statusbayar):
            query = ("UPDATE transaksi_hotel SET statusbayar= WHERE " "('{}')").format(statusbayar)
            cursor.execute(query)
            return redirect('ruangan_hotel:show_transaksi_hotel')
            print('adsadadasda')

        else:
            messages.error(request, 'Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu')
            return redirect(reverse('ruangan_hotel:update_reservasi_hotel'))

    return render(request, 'ubah_transaksi_hotel.html')  

def get_kodehotel():
    cursor = connection.cursor()
    cursor.execute("select kode from hotel;")
    kh_response = dictfetch(cursor)
    return kh_response

def get_koderoom():
    cursor = connection.cursor()
    cursor.execute("select koderoom from hotel h, hotel_room hr WHERE h.kode = hr.kodehotel;") 
    # harus nyambung sm hr
    kr_response = dictfetch(cursor)
    return kr_response

def show_reservasi_hotel(request):
    cursor = connection.cursor()
    query = ('SELECT kodepasien, tglmasuk, tglkeluar, kodehotel, koderoom FROM RESERVASI_HOTEL;')
    cursor.execute(query)
    reservasi_hotel = dictfetchall(cursor)
    context = {'list_reservasi_hotel': reservasi_hotel}
    return render(request, 'list_reservasi_hotel.html', context)

def show_transaksi_hotel(request):
    cursor = connection.cursor()
    query = ('SELECT * FROM TRANSAKSI_HOTEL;')
    cursor.execute(query)
    transaksi_hotel = dictfetchall(cursor)
    context = {'list_transaksi_hotel': transaksi_hotel }
    return render(request, 'list_transaksi_hotel.html', context)

def show_ubah_transaksi_hotel(request, id):
    cursor = connection.cursor()
    query = ("SELECT * FROM TRANSAKSI_HOTEL WHERE idtransaksi=" "('{}')").format(id)
    # query = ("SELECT * FROM TRANSAKSI_HOTEL WHERE idtransaksi=%s", [id])
    cursor.execute(query)
    reservasi_hotel = dictfetchall(cursor)
    context = {'transaksi_hotel': reservasi_hotel[0]}
    return render(request, 'ubah_transaksi_hotel.html', context)

def show_ruangan_hotel(request):
    cursor = connection.cursor()
    query = ('SELECT kodehotel, koderoom, jenisbed, tipe, harga FROM hotel_room;')
    cursor.execute(query)
    reservasi_hotel = dictfetchall(cursor)
    context = {'list_ruangan_hotel': reservasi_hotel}
    return render(request, 'list_ruangan.html', context)

def show_transaksi_booking(request):
    cursor = connection.cursor()
    query = ('SELECT * FROM transaksi_booking;')
    cursor.execute(query)
    transaksi_booking = dictfetchall(cursor)
    context = {'list_transaksi_booking': transaksi_booking }
    return render(request, 'list_transaksi_booking.html', context)

# def delete_room(request, kodehotel, koderoom):
#     hotel_kode = str(kodehotel)
#     room_kode = str(koderoom)
#     cursor = connection.cursor()
#     query = ("SELECT * FROM HOTEL_ROOM WHERE kodehotel= '" +
#              hotel_kode+"' AND koderoom= '"+room_kode+"' ")
#     cursor.execute(query)
#     ubah_isi = dictfetchall(cursor)
#     context = {'list_delete': ubah_isi }
#     if ubah_isi == []:
#         cursor = connection.cursor()
#         query = ("DELETE FROM HOTEL_ROOM WHERE koderoom= '"+room_kode+"'  AND kodehotel= '"+hotel_kode+"' ")
#         cursor.execute(query)
#         messages.success(request, 'Data berhasil dihapus')
#         return redirect('ruangan_hotel:show_ruangan_hotel')
#     else:
#         messages.error(
#             request, 'Data tidak bisa dihapus')
#         return redirect('hotel:show_ruangan_hotel')
#     return render(request, 'list_ruangan_hotel.html')

# def delete_transaksi(request, kodehotel, koderoom):
#     hotel_kode = str(kodehotel)
#     room_kode = str(koderoom)
#     cursor = connection.cursor()
#     query = ("SELECT * FROM HOTEL_ROOM WHERE kodehotel= '" +
#              hotel_kode+"' AND koderoom= '"+room_kode+"' ")
#     cursor.execute(query)
#     ubah_isi = dictfetchall(cursor)
#     if ubah_isi == []:
#         cursor = connection.cursor()
#         query = ("DELETE FROM HOTEL_ROOM WHERE koderoom= '"+room_kode+"'  AND kodehotel= '"+hotel_kode+"' ")
#         cursor.execute(query)
#         messages.success(request, 'Data berhasil dihapus')
#         return redirect('ruangan_hotel:show_ruangan_hotel')
#     else:
#         messages.error(
#             request, 'Data tidak bisa dihapus')
#         return redirect('hotel:show_ruangan_hotel')
#     return render(request, 'list_ruangan_hotel.html')

def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

ruangan_hotel/templates/form_ruangan.html
{% extends "root/base.html" %}
{% block content %}
<form method = 'POST'>
    {% csrf_token %}
    <label for="kodehotel">Kode Hotel</label>
    <select name='kodehotel' id='kodehotel'>
        {% for item in apt %}
        <option> {{item.kode}} </option>
        {% endfor %}
    </select>
    <br>
    <label for="jenisbed">Jenis Bed</label>
    <input type='text' id='jenisbed' name='jenisbed'>
    <br>
    <label for="jenis_bed">Tipe</label>
    <input type='text' id='tipe' name='tipe'>
    <br>
    <label for="jenis_bed">Harga per hari</label>
    <input type='text' id='harga' name='harga'>
    <br>
    <input type='submit' value='SIMPAN'>
</form>



{% endif %}
{% endblock %}

ruangan_hotel/templates/list_reservasi_hotel.html
{% extends "root/base.html" %}
{% block content %}
<table style="width:100%">
    <thead>
        <tr>
        <th>No</th>
        <th>NIK Pasien</th>
        <th>Tanggal Masuk</th>
        <th>Tanggal Keluar</th>
        <th>Kode Hotel</th>
        <th>Ruangan</th>
        {% if request.session.authority == "admin satgas" %}
        <th>Action</th>
        {% endif %}
        </tr>
    </thead>
        {% for i in list_reservasi_hotel %}
        <tbody>
        <th scope="row">{{forloop.counter}}</th>
        <td> {{i.kodepasien}} </td>
        <td> {{i.tglmasuk}} </td>
        <td> {{i.tglkeluar}} </td>
        <td> {{i.kodehotel}} </td>
        <td> {{i.koderoom}} </td>
        {% if request.session.authority == "admin satgas" %}
        <td><button>UPDATE</button><br><button>DELETE</button></td>
        {% endif %}
        </tbody>
        {% endfor %}
  </table>


  {% endblock %}

ruangan_hotel/templates/list_ruangan.html
{% extends "root/base.html" %}
{% block content %}

<table style="width:100%">
    <thead>
        <tr>
        <th>No</th>
        <th>Kode Hotel</th>
        <th>Kode Ruangan</th>
        <th>Jenis Bed</th>
        <th>Tipe</th>
        <th>Harga</th>
        {% if request.session.authority == "admin sistem" %}
        <th>Action</th>
        {% endif %}
        </tr>
    </thead>
        {% for i in list_ruangan_hotel %}
        <tbody>
        <th scope="row">{{forloop.counter}}</th>
        <td> {{i.kodehotel}} </td>
        <td> {{i.koderoom}} </td>
        <td> {{i.jenisbed}} </td>
        <td> {{i.tipe}} </td>
        <td> {{i.harga}} </td>
        {% if request.session.authority == "admin sistem" %}
        <td><button>UPDATE</button><br><button>DELETE</button></td>
        {% endif %}
        </tbody>
        {% endfor %}
  </table>

  {% endblock %}

ruangan_hotel/templates/list_transaksi_booking.html
{% extends "root/base.html" %}
{% block content %}
<table style="width:100%">
    <thead>
        <tr>
        <th>No</th>
        <th>Id Transaksi</th>
        <th>Total Bayar</th>
        <th>Kode Pasien</th>
        <th>Tanggal Masuk</th>
        </tr>
    </thead>
        {% for i in list_transaksi_booking %}
        <tbody>
        <th scope="row">{{forloop.counter}}</th>
        <td> {{i.idtransaksibooking}} </td>
        <td> {{i.totalbayar}} </td>
        <td> {{i.kodepasien}} </td>
        <td> {{i.tglmasuk}} </td>
        </tbody>
        {% endfor %}
  </table>


  {% endblock %}

ruangan_hotel/templates/list_transaksi_hotel.html
<div>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
  </div>

{% extends "root/base.html" %}
{% block content %}
<div class="container-fluid text-center">    
    <table class="table">
        <thead>
            
        <tr>
            <th>Id Transaksi</th>
            <th>Kode Pasien</th>
            <th>Tanggal Pembayaran</th>
            <th>Waktu Pembayaran</th>
            <th>Total Bayar</th>
            <th>Status</th>
            <th> Action</th>

        </tr>
        </thead>
        {% for item in list_transaksi_hotel %}
        <tbody>
        <tr>
            <td>{{ item.idtransaksi }}</td>
            <td>{{ item.kodepasien }}</td>
            {% if item.tanggalpembayaran == null %}
            <td>-</td>
            {% else %}
            <td>{{ item.tanggalpembayaran }}</td>
            {% endif %}
            {% if item.waktupembayaran == null %}
            <td>-</td>
            {% else %}
            <td>{{ item.waktupembayaran }}</td>
            {% endif %}
            <td>{{ item.totalbayar }}</td>
            <td>{{ item.statusbayar}}</td>
            
            <td>
                <a href="{% url 'ruangan_hotel:show_ubah_transaksi_hotel' id=item.idtransaksi %}">
                    <button>UPDATE</button>
                </a>
            </td>

        </tr>
        </tbody>
        {% endfor %}
    </table>
</div>
{% endblock %}

ruangan_hotel/templates/reservasi_hotel.html
{% extends "root/base.html" %}
{% block content %}

<div>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
  </div>

<form method = 'POST'>
    {% csrf_token %}
    <label for="nik">NIK Pasien</label>
    <select name='nik' id='nik'>
        {% for item in nik %}
        <option> {{item.nik}} </option>
        {% endfor %}
    </select>
    <br>
    <label for="tanggalmasuk">Tanggal Masuk</label>
    <input type='date' id='tanggalmasuk' name='tanggalmasuk'>
    <br>
    <label for="tanggalkeluar">Tanggal Keluar</label>
    <input type='date' id='tanggalkeluar' name='tanggalkeluar'>
    <br>
    <label for="kodehotel">Kode Hotel</label>
    <select name='kodehotel' id='kodehotel'>
        {% for item in kh %}
        <option> {{item.kode}} </option>
        {% endfor %}
    </select>
    <br>
    <label for="koderoom">Kode Ruangan</label>
    <select name='koderoom' id='koderoom'>
        {% for item in kr %}
        <option> {{item.koderoom}} </option>
        {% endfor %}
    </select>
    <br>
    <input type='submit' value='SIMPAN'>
</form>

{% endblock %}

ruangan_hotel/templates/ubah_ruangan_hotel.html
{% extends "root/base.html" %}
{% block content %}
<form method = 'POST'>
    {% csrf_token %}
    <label for="kodehotel">Kode Hotel</label>
    <select name='kodehotel' id='kodehotel'>
        {% for item in apt %}
        <option> {{item.kode}} </option>
        {% endfor %}
    </select>
    <br>
    <label for="jenisbed">Jenis Bed</label>
    <input type='text' id='jenisbed' name='jenisbed'>
    <br>
    <label for="jenis_bed">Tipe</label>
    <input type='text' id='tipe' name='tipe'>
    <br>
    <label for="jenis_bed">Harga per hari</label>
    <input type='text' id='harga' name='harga'>
    <br>
    <input type='submit' value='SIMPAN'>
</form>



{% endif %}
{% endblock %}

ruangan_hotel/templates/ubah_transaksi_hotel.html
{% extends "root/base.html" %}
{% block title %}
UBAH TRANSAKSI HOTEL
{% endblock %}
{% block content %}
<p>NIK Pasien= {{ transaksi_hotel.kodepasien }}</p> 
<p>ID Transaksi = {{ transaksi_hotel.idtransaksi }}</p>
<p>Tanggal Pembayaran = {{ transaksi_hotel.tanggalpembayaran }}</p>
<p>Waktu Pembayaran = {{ transaksi_hotel.waktupembayaran}}</p>
<p>Total Biaya = {{ transaksi_hotel.totalbayar }}</p>
<form method = 'POST'>
    {% csrf_token %}
    <p>Status Bayar = </p> <input type='text' id='statusbayar' name='statusbayar'>
    <br>
    <input type='submit' value='SIMPAN' >
</form>
{% endblock %}