hotel/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path

from .views import *

app_name = 'hotel'

urlpatterns = [
    path('create/',
         create_hotel, name='create-hotel'),

    path('show/',
         show_hotel, name='show-hotel'),

    path('ubah/<str:kode>',
         ubah_hotel, name='ubah-hotel'),

    path('create-makan/',
         create_makan, name='create-makan'),

    path('show-makan/',
         show_makan, name='show-makan'),

    path('ubah-makan/<str:kode_hot>/<str:kode_pak>',
         ubah_makan, name='ubah-makan'),

    path('delete-makan/<str:kode_hot>/<str:kode_pak>',
         delete_makan, name='delete-makan'),

    path('create-trans-makan/',
         create_trans_makan, name='create-trans-makan'),

    path('show-trans-makan/',
         show_trans_makan, name='show-trans-makan'),

    path('ubah-trans-makan/',
         ubah_trans_makan, name='ubah-trans-makan'),

    path('detail-trans-makan/<str:idtr>/<str:idtm>',
         detail_trans_makan, name='detail-trans-makan'),

]

siruco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('trigger3/', include ('trigger3.urls')),
    path("", include('dashboard.urls')),
    path('transaksi/', include('transaksi_hotel.urls')),
    path('transaksi/', include('transaksi_rs.urls')),
    path('pasien/', include('hasiltespasien.urls')),
    path("hotel/", include('ruangan_hotel.urls')),
    path("", include('dashboard.urls')),
    path("hotel/", include('ruangan_hotel.urls')),
    path("pengguna-publik/", include('crudpasienpenggunapublik.urls')),
    path("jadwal-dokter/", include('crjadwaldokter.urls')),
    path("appointment/", include('crudappointmentwithdoctor.urls')),
    path("ruangan-bed/", include('crudruanganbed.urls')),
    path('pasien/', include('hasiltespasien.urls')),
    path('hotel/', include('hotel.urls'))
]

transaksi_rs/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='transaksi_rs'

urlpatterns = [
    path('transaksi_rs',views.display_transaksi_rs,name='display-transaksi-rs'),
    path('transaksi_rs/detail/<str:id>',views.detail_transaksi_rs,name='detail-transaksi-rs'),
    path('transaksi_rs/<str:id>',views.update_transaksi_rs,name='update-transaksi-rs'),
]

transaksi_rs/models.py
from django.db import models

# Create your models here.

transaksi_rs/views.py
from django.http import response
from django.shortcuts import render, redirect, HttpResponse
from django.db import connection
from django.views.decorators.csrf import csrf_exempt
import datetime

#method ini cmn buat pengguna_publik
def display_transaksi_rs(request):
    username = request.session['username']
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco;")
    if(request.session['authority'] == 'pengguna publik'):
        cursor.execute("select * from transaksi_rs t join pasien p on p.nik = t.kodepasien join pengguna_publik pp on p.idpendaftar = pp.username where pp.username=%s;", [username])
    else:
        cursor.execute("select * from transaksi_rs")

    transaksi_rs_response = dictfetch(cursor)
    context = {'apt' : transaksi_rs_response}
    # print(context)
    return render(request,'transaksi_rs.html', context)

def detail_transaksi_rs(request,id):
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco;")
    cursor.execute("select * from transaksi_rs t natural join reservasi_rs r join faskes f on r.koders = f.kode where t.idtransaksi=%s;",[id])
    detail_transaksi_hotel = dictfetch(cursor)
    context = {'apt' : detail_transaksi_hotel[0]}
    # print(context)
    return render(request, 'detail_transaksi_rs.html', context)

def update_transaksi_rs(request,id):
    username = request.session['username']
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco;")
    cursor.execute("update transaksi_rs set statusbayar = 'Lunas', tanggalpembayaran = now(), waktupembayaran = date_trunc('hour',now()) where idtransaksi=%s;",[id])
    cursor.execute("select * from transaksi_rs t join pasien p on p.nik = t.kodepasien join pengguna_publik pp on p.idpendaftar = pp.username where pp.username=%s;", [username])
    transaksi_rs_response = dictfetch(cursor)
    context = {'apt' : transaksi_rs_response}
    
    return render (request,'transaksi_rs.html', context)

# https://docs.djangoproject.com/en/3.2/topics/db/sql/
def dictfetch(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

transaksi_rs/templates/detail_transaksi_rs.html
{% extends "root/base.html" %}
{% block title %}
DETAIL TRANSAKSI RS
{% endblock %}
{% block content %}
  
<div class="card">
    <div class="card-header">
      DATA TRANSAKSI RUMAH SAKIT
    </div>
    <div class="card-body">
      <p class="card-text">
          NIK Pasien: {{apt.kodepasien}} 
          <br>
          Id Transaksi: {{apt.idtransaksi}}
          <br>
          Tanggal Pembayaran: {{apt.tanggalpembayaran}}
          <br>
          Waktu Pembayaran: {{apt.waktupembayaran}}
          <br>
          Total Biaya: {{apt.totalbiaya}}
          <br>
          Status Bayar: {{apt.statusbayar}}
          <br>
          <br>
          Data Reservasi:
          <br>
          Tanggal Masuk: {{apt.tglmasuk}}
          <br>
          Tanggal Keluar: {{apt.tglkeluar}}
          <br>
          Nama - ID Rumah Sakit: {{apt.nama}} - {{apt.koders}}
          <br>
          Ruangan: {{apt.koderuangan}}
          <br>
          Bed: {{apt.kodebed}}
          <br>
        </p>
      <a href="{% url 'transaksi_rs:display-transaksi-rs' %}" class="btn btn-primary">KEMBALI</a>
    </div>
  </div>

  {% endblock %}

transaksi_rs/templates/transaksi_rs.html
{% extends "root/base.html" %}

{% block title %}
TRANSAKSI RS
{% endblock %}
{% block content %}
  
<div class="container-fluid text-center">    
    <table class="table">
        <thead>
            
        <tr>
            <th>Id Transaksi</th>
            <th>Kode Pasien</th>
            <th>Tanggal Pembayaran</th>
            <th>Tanggal Masuk </th>
            <th>Total Biaya</th>
            <th>Status</th>
            <th> Action</th>
            <!-- {% if request.session.is_staf %}
            <th>Action</th>
            {% endif %} -->
        </tr>
        </thead>
        {% for item in apt %}
        <tbody>
        <tr>
            <td>{{ item.idtransaksi }}</td>
            <td>{{ item.kodepasien }}</td>
            {% if item.tanggalpembayaran == null %}
            <td>-</td>
            {% else %}
            <td>{{ item.tanggalpembayaran }}</td>
            {% endif %}
            <td>{{ item.tglmasuk }}</td>
            <td>{{ item.totalbiaya}}</td>
            <td>{{ item.statusbayar}}</td>
            <td>
                <a href="{% url 'transaksi_rs:detail-transaksi-rs' id=item.idtransaksi %}">
                    <button>DETAIL</button>
                </a>
                <br>
                {% if item.statusbayar == "Belum Lunas" and request.session.authority == "pengguna publik" %}
                <a href="{% url 'transaksi_rs:update-transaksi-rs' id=item.idtransaksi %}">
                    <button>KONFIRMASI PEMBAYARAN</button>
                </a>
                {% endif %}
            </td>

        </tr>
        </tbody>
        {% endfor %}
    </table>
</div>

{% endblock %}